# port
server:
  port: 8888
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true

spring:
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud-disk?serverTimezone=Asia/Shanghai&useSSL=false&characterEncoding=utf-8
    # ENC(Fa8ZkoaXeRu7wKJD/WBEvB5y92ze99nWGUKAUy2RXgP0AAFAQQTM9r0LjTit+wOeAwY1XI01V+9WytXyDM30hkwmGBoeA/WpUuVOiKTf033H62g/tMYNH8qT8VY4sUfOUO3d8EpwU40=)
    username: root
    password: 111111 # ENC(ZUR23UX/fzqJqlZpal/bqgKOsqX/OqMJ)  # Cai@1995

  # redis
  redis:
    host: 121.36.32.117 #ENC(okxOoOtJksvAvsggGgCx+fFpsCGqdGbT)
    port: 6379
    password: 123456 # ENC(hljY8XsGfD5fhZP4AUHU/A==)
    # 上传文件的配置
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  # 取消thymeleaf的缓存 开发阶段
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:e:/upload/

# mybatis
mybatis:
  # mapper文件路径
  mapper-locations: classpath:mapper/*.xml
  # 别名
  type-aliases-package: com.tomcai.cloud.pojo
  configuration:
    # 驼峰命名
    map-underscore-to-camel-case: true
#加密工具盐值
#jasypt:
#  encryptor:
#    password: /1uqR0vXxA2tSM9HCtSW4A== # ENC(tomcai)

##自定义参数
# 文件上传下载配置
file:
  # 自定义文件上传路径
  upload:
    dir: e:/upload/
  #设置下载缓存的大小 单位字节
  download:
    bufferSize: 2097152 # 1024*1024*2 2M的缓存
